import axios from 'axios';
import { db, apiUsage } from '@leadnex/database';
import { logger } from '../../utils/logger';
import { settingsService } from '../settings.service';
import type { Lead, LeadSource } from '@leadnex/shared';

const APOLLO_API_BASE = 'https://api.apollo.io/v1';

interface ApolloSearchParams {
  industry: string;
  country?: string;
  city?: string;
  maxResults?: number;
}

interface ApolloContact {
  id: string;
  first_name: string;
  last_name: string;
  title: string;
  email: string;
  organization: {
    name: string;
    website_url: string;
    industry: string;
    estimated_num_employees: number;
    primary_phone?: {
      number: string;
    };
  };
  city: string;
  state: string;
  country: string;
}

export class ApolloService {
  private async getApiKey(): Promise<string> {
    const apiKey = await settingsService.get('apolloApiKey', process.env.APOLLO_API_KEY);
    if (!apiKey) {
      throw new Error('APOLLO_API_KEY is not configured. Please set it in Settings or .env file');
    }
    return apiKey;
  }

  /**
   * Search for leads using Apollo.io People Search API
   * Using /people/search endpoint which is available on free plan
   */
  async searchLeads(params: ApolloSearchParams): Promise<Lead[]> {
    try {
      const apiKey = await this.getApiKey();
      logger.info('[Apollo] Searching for leads', { params });

      // Build search query for /people/search endpoint (free tier compatible)
      const searchQuery: any = {
        page: 1,
        per_page: Math.min(params.maxResults || 10, 25), // Free tier limit
        person_titles: [
          'owner',
          'founder',
          'ceo',
          'manager',
          'director',
          'president',
          'co-founder',
          'chief executive officer',
        ],
      };

      // Add organization keywords (industry)
      if (params.industry) {
        searchQuery.organization_industry_tag_ids = [params.industry.toLowerCase()];
      }

      // Add location filters
      if (params.country) {
        searchQuery.person_locations = [params.country];
      }
      
      if (params.city) {
        searchQuery.person_locations = [`${params.city}, ${params.country || ''}`];
      }

      // Apollo requires API key in X-Api-Key header (free tier compatible)
      const response = await axios.post(
        `${APOLLO_API_BASE}/people/search`,
        searchQuery,
        {
          headers: {
            'Content-Type': 'application/json',
            'Cache-Control': 'no-cache',
            'X-Api-Key': apiKey,
          },
          timeout: 30000,
        }
      );

      if (!response.data || !response.data.people) {
        logger.warn('[Apollo] No people found in response');
        return [];
      }

      logger.info(`[Apollo] Found ${response.data.people.length} people from Apollo.io`);

      const leads: Lead[] = response.data.people.map((person: ApolloContact) => {
        const lead: Partial<Lead> = {
          id: '', // Will be generated by database
          companyName: person.organization?.name || 'Unknown Company',
          website: person.organization?.website_url,
          email: person.email,
          phone: person.organization?.primary_phone?.number,
          contactName: `${person.first_name} ${person.last_name}`.trim(),
          jobTitle: person.title,
          city: person.city,
          country: person.country,
          industry: params.industry,
          companySize: this.mapCompanySize(person.organization?.estimated_num_employees),
          source: 'apollo' as LeadSource,
          qualityScore: 0, // Will be calculated later
          verificationStatus: person.email ? 'email_verified' : 'unverified',
          status: 'new',
          followUpStage: 'initial',
          emailsSent: 0,
          emailsOpened: 0,
          emailsClicked: 0,
          customFields: {
            apolloId: person.id,
            apolloData: {
              firstName: person.first_name,
              lastName: person.last_name,
              title: person.title,
              estimatedEmployees: person.organization?.estimated_num_employees,
            },
          },
          createdAt: new Date(),
          updatedAt: new Date(),
        };

        return lead as Lead;
      });

      // Track API usage
      await this.trackApiUsage(leads.length);

      logger.info('[Apollo] Successfully fetched leads', {
        count: leads.length,
        industry: params.industry,
      });

      return leads;
    } catch (error: any) {
      logger.error('[Apollo] Error fetching leads', {
        error: error.message,
        response: error.response?.data,
      });

      // Check if rate limit exceeded
      if (error.response?.status === 429) {
        throw new Error('Apollo API rate limit exceeded. Please try again later.');
      }

      // Check if API key is invalid
      if (error.response?.status === 401) {
        throw new Error('Invalid Apollo API key. Please check your configuration.');
      }

      throw new Error(`Apollo API error: ${error.message}`);
    }
  }

  /**
   * Map company employee count to size category
   */
  private mapCompanySize(employeeCount?: number): string {
    if (!employeeCount) return '1-10';
    
    if (employeeCount <= 10) return '1-10';
    if (employeeCount <= 50) return '11-50';
    if (employeeCount <= 200) return '51-200';
    if (employeeCount <= 500) return '201-500';
    if (employeeCount <= 1000) return '501-1000';
    return '1000+';
  }

  /**
   * Check remaining API credits
   */
  async checkApiUsage(): Promise<{ used: number; remaining: number }> {
    try {
      // Apollo doesn't provide a direct usage endpoint in free tier
      // This is a placeholder - you may need to track usage locally
      return {
        used: 0,
        remaining: 100, // Free tier limit
      };
    } catch (error: any) {
      logger.error('[Apollo] Error checking API usage', { error: error.message });
      throw error;
    }
  }

  /**
   * Track API usage in database
   */
  private async trackApiUsage(leadsFetched: number): Promise<void> {
    try {
      const now = new Date();
      const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());
      const endOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);

      await db.insert(apiUsage).values({
        service: 'apollo',
        requestsMade: leadsFetched,
        requestsLimit: 100, // Daily limit
        periodStart: startOfDay,
        periodEnd: endOfDay,
        createdAt: new Date(),
      });
    } catch (error: any) {
      logger.error('[Apollo] Error tracking API usage', {
        error: error.message,
      });
    }
  }

  /**
   * Enrich a single lead with additional data
   */
  async enrichLead(params: {
    email?: string;
    companyName?: string;
    domain?: string;
  }): Promise<any> {
    try {
      const apiKey = await this.getApiKey();
      logger.info('[Apollo] Enriching lead', { params });

      // Build enrichment query (DO NOT include api_key in body)
      const enrichQuery: any = {};

      if (params.email) {
        enrichQuery.email = params.email;
      } else if (params.domain) {
        enrichQuery.domain = params.domain;
      } else {
        throw new Error('Either email or domain is required for enrichment');
      }

      // Apollo requires API key in X-Api-Key header
      const response = await axios.post(
        `${APOLLO_API_BASE}/people/match`,
        enrichQuery,
        {
          headers: {
            'Content-Type': 'application/json',
            'X-Api-Key': apiKey,
          },
          timeout: 15000,
        }
      );

      if (!response.data || !response.data.person) {
        logger.warn('[Apollo] No enrichment data found');
        return null;
      }

      const person = response.data.person;
      return {
        email: person.email,
        phone: person.phone_numbers?.[0],
        linkedin: person.linkedin_url,
        jobTitle: person.title,
        seniority: person.seniority,
        department: person.functions,
        companyName: person.organization?.name,
        companyIndustry: person.organization?.industry,
        companySize: person.organization?.estimated_num_employees,
      };
    } catch (error: any) {
      logger.error('[Apollo] Error enriching lead', {
        error: error.message,
        response: error.response?.data,
      });
      return null;
    }
  }
}

export const apolloService = new ApolloService();
