import axios from 'axios';
import { logger } from '../../utils/logger';
import type { Lead, LeadSource } from '@leadnex/shared';

const APOLLO_API_BASE = 'https://api.apollo.io/v1';
const APOLLO_API_KEY = process.env.APOLLO_API_KEY;

interface ApolloSearchParams {
  industry: string;
  country?: string;
  city?: string;
  maxResults?: number;
}

interface ApolloContact {
  id: string;
  first_name: string;
  last_name: string;
  title: string;
  email: string;
  organization: {
    name: string;
    website_url: string;
    industry: string;
    estimated_num_employees: number;
    primary_phone?: {
      number: string;
    };
  };
  city: string;
  state: string;
  country: string;
}

export class ApolloService {
  private apiKey: string;

  constructor() {
    if (!APOLLO_API_KEY) {
      throw new Error('APOLLO_API_KEY is not set in environment variables');
    }
    this.apiKey = APOLLO_API_KEY;
  }

  /**
   * Search for leads using Apollo.io People Search API
   */
  async searchLeads(params: ApolloSearchParams): Promise<Lead[]> {
    try {
      logger.info('[Apollo] Searching for leads', { params });

      const searchQuery: any = {
        api_key: this.apiKey,
        q_organization_keyword_tags: [params.industry],
        per_page: Math.min(params.maxResults || 10, 100),
        page: 1,
      };

      // Add location filters
      if (params.country) {
        searchQuery.person_locations = [params.country];
      }
      
      if (params.city) {
        searchQuery.person_locations = [`${params.city}, ${params.country || ''}`];
      }

      // Search for decision makers (owners, managers, directors)
      searchQuery.person_titles = [
        'owner',
        'founder',
        'ceo',
        'manager',
        'director',
        'president',
      ];

      const response = await axios.post(
        `${APOLLO_API_BASE}/mixed_people/search`,
        searchQuery,
        {
          headers: {
            'Content-Type': 'application/json',
            'Cache-Control': 'no-cache',
          },
          timeout: 30000,
        }
      );

      if (!response.data || !response.data.people) {
        logger.warn('[Apollo] No people found in response');
        return [];
      }

      const leads: Lead[] = response.data.people.map((person: ApolloContact) => {
        const lead: Partial<Lead> = {
          id: '', // Will be generated by database
          companyName: person.organization?.name || 'Unknown Company',
          website: person.organization?.website_url,
          email: person.email,
          phone: person.organization?.primary_phone?.number,
          contactName: `${person.first_name} ${person.last_name}`.trim(),
          jobTitle: person.title,
          city: person.city,
          country: person.country,
          industry: params.industry,
          companySize: this.mapCompanySize(person.organization?.estimated_num_employees),
          source: 'apollo' as LeadSource,
          qualityScore: 0, // Will be calculated later
          verificationStatus: person.email ? 'email_verified' : 'unverified',
          status: 'new',
          followUpStage: 'initial',
          emailsSent: 0,
          emailsOpened: 0,
          emailsClicked: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
        };

        return lead as Lead;
      });

      logger.info('[Apollo] Successfully fetched leads', {
        count: leads.length,
        industry: params.industry,
      });

      return leads;
    } catch (error: any) {
      logger.error('[Apollo] Error fetching leads', {
        error: error.message,
        response: error.response?.data,
      });

      // Check if rate limit exceeded
      if (error.response?.status === 429) {
        throw new Error('Apollo API rate limit exceeded. Please try again later.');
      }

      // Check if API key is invalid
      if (error.response?.status === 401) {
        throw new Error('Invalid Apollo API key. Please check your configuration.');
      }

      throw new Error(`Apollo API error: ${error.message}`);
    }
  }

  /**
   * Map company employee count to size category
   */
  private mapCompanySize(employeeCount?: number): string {
    if (!employeeCount) return '1-10';
    
    if (employeeCount <= 10) return '1-10';
    if (employeeCount <= 50) return '11-50';
    if (employeeCount <= 200) return '51-200';
    if (employeeCount <= 500) return '201-500';
    if (employeeCount <= 1000) return '501-1000';
    return '1000+';
  }

  /**
   * Check remaining API credits
   */
  async checkApiUsage(): Promise<{ used: number; remaining: number }> {
    try {
      // Apollo doesn't provide a direct usage endpoint in free tier
      // This is a placeholder - you may need to track usage locally
      return {
        used: 0,
        remaining: 100, // Free tier limit
      };
    } catch (error: any) {
      logger.error('[Apollo] Error checking API usage', { error: error.message });
      throw error;
    }
  }
}

export const apolloService = new ApolloService();
